# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-03-31 11:14:24
"""
import arcpy
from sys import argv
def #  NOT  IMPLEMENTED# Function Body not implemented

def DynamicMultivalueDropDownListSubModel(Input_Table="C:\\Users\\jtouzel\\Downloads\\ChooseFieldValue\\ToolData\\ToolData.gdb\\BirdLocations", Values_To_Iterate=["Black Scoter"]):  # Choose Multiple Field Value Sub Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False


    for Value in #  NOT  IMPLEMENTED(Values_To_Iterate):

        # Process: Calculate Value (Calculate Value) 
        Name = "Value".replace(" ", "")[0]

        # Process: Select (Select) 
        Name = "BlackScoter"
        Select_Output = fr"C:\Users\jtouzel\Downloads\ChooseMultipleFieldValues\Scratch\Scratch.gdb\{Name}"
        if Name and Value:
            arcpy.Select_analysis(in_features=Input_Table, out_feature_class=Select_Output, where_clause=f"\"Type\" = '{Value}'")

        # Process: Collect_Values (Collect Values) 
        # Collect Values Utility is not implemented 

        return Output_Values

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\Users\jtouzel\Documents\ArcGIS\Projects\ProjectTemplate\ProjectTemplate.gdb", workspace=r"C:\Users\jtouzel\Documents\ArcGIS\Projects\ProjectTemplate\ProjectTemplate.gdb"):
        DynamicMultivalueDropDownListSubModel(*argv[1:])
